// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: buycar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCarSaleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Brand    string `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Model    string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	SellerID int64  `protobuf:"varint,3,opt,name=sellerID,proto3" json:"sellerID,omitempty"`
}

func (x *CreateCarSaleRequest) Reset() {
	*x = CreateCarSaleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCarSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCarSaleRequest) ProtoMessage() {}

func (x *CreateCarSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCarSaleRequest.ProtoReflect.Descriptor instead.
func (*CreateCarSaleRequest) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCarSaleRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateCarSaleRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateCarSaleRequest) GetSellerID() int64 {
	if x != nil {
		return x.SellerID
	}
	return 0
}

type CreateCarSaleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateCarSaleResponse) Reset() {
	*x = CreateCarSaleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCarSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCarSaleResponse) ProtoMessage() {}

func (x *CreateCarSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCarSaleResponse.ProtoReflect.Descriptor instead.
func (*CreateCarSaleResponse) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCarSaleResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateCarSaleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarSale *CarSale `protobuf:"bytes,1,opt,name=carSale,proto3" json:"carSale,omitempty"`
}

func (x *UpdateCarSaleRequest) Reset() {
	*x = UpdateCarSaleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCarSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCarSaleRequest) ProtoMessage() {}

func (x *UpdateCarSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCarSaleRequest.ProtoReflect.Descriptor instead.
func (*UpdateCarSaleRequest) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCarSaleRequest) GetCarSale() *CarSale {
	if x != nil {
		return x.CarSale
	}
	return nil
}

type UpdateCarSaleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *UpdateCarSaleResponse) Reset() {
	*x = UpdateCarSaleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCarSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCarSaleResponse) ProtoMessage() {}

func (x *UpdateCarSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCarSaleResponse.ProtoReflect.Descriptor instead.
func (*UpdateCarSaleResponse) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateCarSaleResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeleteCarSaleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteCarSaleRequest) Reset() {
	*x = DeleteCarSaleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCarSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCarSaleRequest) ProtoMessage() {}

func (x *DeleteCarSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCarSaleRequest.ProtoReflect.Descriptor instead.
func (*DeleteCarSaleRequest) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCarSaleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCarSaleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *DeleteCarSaleResponse) Reset() {
	*x = DeleteCarSaleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCarSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCarSaleResponse) ProtoMessage() {}

func (x *DeleteCarSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCarSaleResponse.ProtoReflect.Descriptor instead.
func (*DeleteCarSaleResponse) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCarSaleResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetCarSaleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCarSaleRequest) Reset() {
	*x = GetCarSaleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCarSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCarSaleRequest) ProtoMessage() {}

func (x *GetCarSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCarSaleRequest.ProtoReflect.Descriptor instead.
func (*GetCarSaleRequest) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{6}
}

func (x *GetCarSaleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCarSaleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CarSale *CarSale `protobuf:"bytes,1,opt,name=carSale,proto3" json:"carSale,omitempty"`
}

func (x *GetCarSaleResponse) Reset() {
	*x = GetCarSaleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCarSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCarSaleResponse) ProtoMessage() {}

func (x *GetCarSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCarSaleResponse.ProtoReflect.Descriptor instead.
func (*GetCarSaleResponse) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{7}
}

func (x *GetCarSaleResponse) GetCarSale() *CarSale {
	if x != nil {
		return x.CarSale
	}
	return nil
}

type CarSale struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Brand    string `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model    string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	SellerID int64  `protobuf:"varint,4,opt,name=sellerID,proto3" json:"sellerID,omitempty"`
}

func (x *CarSale) Reset() {
	*x = CarSale{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarSale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarSale) ProtoMessage() {}

func (x *CarSale) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarSale.ProtoReflect.Descriptor instead.
func (*CarSale) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{8}
}

func (x *CarSale) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CarSale) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CarSale) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CarSale) GetSellerID() int64 {
	if x != nil {
		return x.SellerID
	}
	return 0
}

type CreateSellerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber string `protobuf:"bytes,2,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
}

func (x *CreateSellerRequest) Reset() {
	*x = CreateSellerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSellerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSellerRequest) ProtoMessage() {}

func (x *CreateSellerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSellerRequest.ProtoReflect.Descriptor instead.
func (*CreateSellerRequest) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSellerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSellerRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type CreateSellerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateSellerResponse) Reset() {
	*x = CreateSellerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSellerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSellerResponse) ProtoMessage() {}

func (x *CreateSellerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSellerResponse.ProtoReflect.Descriptor instead.
func (*CreateSellerResponse) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{10}
}

func (x *CreateSellerResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateSellerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seller *Seller `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
}

func (x *UpdateSellerRequest) Reset() {
	*x = UpdateSellerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSellerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSellerRequest) ProtoMessage() {}

func (x *UpdateSellerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSellerRequest.ProtoReflect.Descriptor instead.
func (*UpdateSellerRequest) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateSellerRequest) GetSeller() *Seller {
	if x != nil {
		return x.Seller
	}
	return nil
}

type UpdateSellerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *UpdateSellerResponse) Reset() {
	*x = UpdateSellerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSellerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSellerResponse) ProtoMessage() {}

func (x *UpdateSellerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSellerResponse.ProtoReflect.Descriptor instead.
func (*UpdateSellerResponse) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSellerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeleteSellerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteSellerRequest) Reset() {
	*x = DeleteSellerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSellerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSellerRequest) ProtoMessage() {}

func (x *DeleteSellerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSellerRequest.ProtoReflect.Descriptor instead.
func (*DeleteSellerRequest) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSellerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteSellerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *DeleteSellerResponse) Reset() {
	*x = DeleteSellerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSellerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSellerResponse) ProtoMessage() {}

func (x *DeleteSellerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSellerResponse.ProtoReflect.Descriptor instead.
func (*DeleteSellerResponse) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteSellerResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetSellerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSellerRequest) Reset() {
	*x = GetSellerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSellerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellerRequest) ProtoMessage() {}

func (x *GetSellerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellerRequest.ProtoReflect.Descriptor instead.
func (*GetSellerRequest) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{15}
}

func (x *GetSellerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSellerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seller *Seller `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
}

func (x *GetSellerResponse) Reset() {
	*x = GetSellerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSellerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSellerResponse) ProtoMessage() {}

func (x *GetSellerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSellerResponse.ProtoReflect.Descriptor instead.
func (*GetSellerResponse) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{16}
}

func (x *GetSellerResponse) GetSeller() *Seller {
	if x != nil {
		return x.Seller
	}
	return nil
}

type Seller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber string `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
}

func (x *Seller) Reset() {
	*x = Seller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_buycar_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Seller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seller) ProtoMessage() {}

func (x *Seller) ProtoReflect() protoreflect.Message {
	mi := &file_buycar_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seller.ProtoReflect.Descriptor instead.
func (*Seller) Descriptor() ([]byte, []int) {
	return file_buycar_proto_rawDescGZIP(), []int{17}
}

func (x *Seller) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Seller) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Seller) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

var File_buycar_proto protoreflect.FileDescriptor

var file_buycar_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x62, 0x75, 0x79, 0x63, 0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x74, 0x6f, 0x64, 0x6f, 0x22, 0x5e, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61,
	0x72, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x62, 0x72, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61,
	0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x6c,
	0x65, 0x72, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x6c,
	0x65, 0x72, 0x49, 0x44, 0x22, 0x27, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61,
	0x72, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3f, 0x0a,
	0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x43, 0x61,
	0x72, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x07, 0x63, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x22, 0x27,
	0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x26, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3d, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x53,
	0x61, 0x6c, 0x65, 0x52, 0x07, 0x63, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x22, 0x61, 0x0a, 0x07,
	0x43, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x72, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x44, 0x22,
	0x4b, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x68,
	0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x26, 0x0a, 0x14,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a, 0x06, 0x73,
	0x65, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x6f,
	0x64, 0x6f, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65,
	0x72, 0x22, 0x26, 0x0a, 0x14, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x25, 0x0a, 0x13, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x26, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x22, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53,
	0x65, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x24, 0x0a, 0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x52,
	0x06, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x22, 0x4e, 0x0a, 0x06, 0x53, 0x65, 0x6c, 0x6c, 0x65,
	0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x32, 0xd1, 0x04, 0x0a, 0x0d, 0x42, 0x75, 0x79, 0x43,
	0x61, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0d, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x74, 0x6f, 0x64,
	0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43,
	0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x43, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x43, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x4a, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x72, 0x53, 0x61,
	0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x43, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x61, 0x72, 0x53,
	0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a,
	0x0a, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x12, 0x17, 0x2e, 0x74, 0x6f,
	0x64, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x61, 0x72, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x47, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72,
	0x12, 0x19, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65,
	0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x74, 0x6f,
	0x64, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0c, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x74, 0x6f, 0x64, 0x6f,
	0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x47, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c,
	0x65, 0x72, 0x12, 0x19, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x65, 0x6c, 0x6c, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x65, 0x6c, 0x6c, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_buycar_proto_rawDescOnce sync.Once
	file_buycar_proto_rawDescData = file_buycar_proto_rawDesc
)

func file_buycar_proto_rawDescGZIP() []byte {
	file_buycar_proto_rawDescOnce.Do(func() {
		file_buycar_proto_rawDescData = protoimpl.X.CompressGZIP(file_buycar_proto_rawDescData)
	})
	return file_buycar_proto_rawDescData
}

var file_buycar_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_buycar_proto_goTypes = []interface{}{
	(*CreateCarSaleRequest)(nil),  // 0: todo.CreateCarSaleRequest
	(*CreateCarSaleResponse)(nil), // 1: todo.CreateCarSaleResponse
	(*UpdateCarSaleRequest)(nil),  // 2: todo.UpdateCarSaleRequest
	(*UpdateCarSaleResponse)(nil), // 3: todo.UpdateCarSaleResponse
	(*DeleteCarSaleRequest)(nil),  // 4: todo.DeleteCarSaleRequest
	(*DeleteCarSaleResponse)(nil), // 5: todo.DeleteCarSaleResponse
	(*GetCarSaleRequest)(nil),     // 6: todo.GetCarSaleRequest
	(*GetCarSaleResponse)(nil),    // 7: todo.GetCarSaleResponse
	(*CarSale)(nil),               // 8: todo.CarSale
	(*CreateSellerRequest)(nil),   // 9: todo.CreateSellerRequest
	(*CreateSellerResponse)(nil),  // 10: todo.CreateSellerResponse
	(*UpdateSellerRequest)(nil),   // 11: todo.UpdateSellerRequest
	(*UpdateSellerResponse)(nil),  // 12: todo.UpdateSellerResponse
	(*DeleteSellerRequest)(nil),   // 13: todo.DeleteSellerRequest
	(*DeleteSellerResponse)(nil),  // 14: todo.DeleteSellerResponse
	(*GetSellerRequest)(nil),      // 15: todo.GetSellerRequest
	(*GetSellerResponse)(nil),     // 16: todo.GetSellerResponse
	(*Seller)(nil),                // 17: todo.Seller
}
var file_buycar_proto_depIdxs = []int32{
	8,  // 0: todo.UpdateCarSaleRequest.carSale:type_name -> todo.CarSale
	8,  // 1: todo.GetCarSaleResponse.carSale:type_name -> todo.CarSale
	17, // 2: todo.UpdateSellerRequest.seller:type_name -> todo.Seller
	17, // 3: todo.GetSellerResponse.seller:type_name -> todo.Seller
	0,  // 4: todo.BuyCarService.CreateCarSale:input_type -> todo.CreateCarSaleRequest
	2,  // 5: todo.BuyCarService.UpdateCarSale:input_type -> todo.UpdateCarSaleRequest
	4,  // 6: todo.BuyCarService.DeleteCarSale:input_type -> todo.DeleteCarSaleRequest
	6,  // 7: todo.BuyCarService.GetCarSale:input_type -> todo.GetCarSaleRequest
	9,  // 8: todo.BuyCarService.CreateSeller:input_type -> todo.CreateSellerRequest
	11, // 9: todo.BuyCarService.UpdateSeller:input_type -> todo.UpdateSellerRequest
	13, // 10: todo.BuyCarService.DeleteSeller:input_type -> todo.DeleteSellerRequest
	15, // 11: todo.BuyCarService.GetSeller:input_type -> todo.GetSellerRequest
	1,  // 12: todo.BuyCarService.CreateCarSale:output_type -> todo.CreateCarSaleResponse
	3,  // 13: todo.BuyCarService.UpdateCarSale:output_type -> todo.UpdateCarSaleResponse
	5,  // 14: todo.BuyCarService.DeleteCarSale:output_type -> todo.DeleteCarSaleResponse
	7,  // 15: todo.BuyCarService.GetCarSale:output_type -> todo.GetCarSaleResponse
	10, // 16: todo.BuyCarService.CreateSeller:output_type -> todo.CreateSellerResponse
	12, // 17: todo.BuyCarService.UpdateSeller:output_type -> todo.UpdateSellerResponse
	14, // 18: todo.BuyCarService.DeleteSeller:output_type -> todo.DeleteSellerResponse
	16, // 19: todo.BuyCarService.GetSeller:output_type -> todo.GetSellerResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_buycar_proto_init() }
func file_buycar_proto_init() {
	if File_buycar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_buycar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCarSaleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCarSaleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCarSaleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCarSaleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCarSaleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCarSaleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCarSaleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCarSaleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarSale); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSellerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSellerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSellerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSellerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSellerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSellerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSellerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSellerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_buycar_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Seller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_buycar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_buycar_proto_goTypes,
		DependencyIndexes: file_buycar_proto_depIdxs,
		MessageInfos:      file_buycar_proto_msgTypes,
	}.Build()
	File_buycar_proto = out.File
	file_buycar_proto_rawDesc = nil
	file_buycar_proto_goTypes = nil
	file_buycar_proto_depIdxs = nil
}
